CREATE TABLE IF NOT EXISTS ROLES (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL UNIQUE);
	
INSERT INTO ROLES VALUES(1,'ROLE_USER');
INSERT INTO ROLES VALUES(2,'ROLE_AUTHOR');
INSERT INTO ROLES VALUES(3,'ROLE_ADMIN');

CREATE TABLE IF NOT EXISTS USERS (
	ID INTEGER PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(200) NOT NULL,
	ROLE INTEGER NOT NULL,
	FOREIGN KEY(ROLE) REFERENCES ROLES(ID));

CREATE TABLE IF NOT EXISTS ARTICLES (
	ID INTEGER PRIMARY KEY,
	SUBJECT VARCHAR(100) NOT NULL,
	BODY VARCHAR(1000),
	AUTHOR INTEGER NOT NULL,
	CREATED_ON TIMESTAMP,
	FOREIGN KEY(AUTHOR) REFERENCES USERS(ID));
	
CREATE SEQUENCE IF NOT EXISTS USER_ID
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;
    
CREATE SEQUENCE IF NOT EXISTS ARTICLE_ID
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;
